helm:
  parameters:
  - name: guestbook.image
    value: gcr.io/heptio-images/ks-guestbook-demo
    forcestring: true
  - name: guestbook.tag
    value: "0.2"
    forcestring: true
  - name: image.name
    value: nginx
    forcestring: true
  - name: image.tag
    value: "1.20"
    forcestring: true
