apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 1 
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: "{{ .Values.guestbook.image.repository }}:{{ .Values.guestbook.image.tag }}"
        imagePullPolicy: {{ .Values.guestbook.pullPolicy }}
        ports:
        - containerPort: 80
